# R - Matrices

Matrices are the R objects in which the elements are arranged in a two-dimensional rectangular layout. They contain elements of the same atomic types. Though we can create a matrix containing only characters or only logical values, they are not of much use. We use matrices containing numeric elements to be used in mathematical calculations.

A Matrix is created using the <b>matrix()</b> function.

## Syntax
The basic syntax for creating a matrix in R is −

####  matrix(data, nrow, ncol, byrow, dimnames)

Following is the description of the parameters used −

* data is the input vector which becomes the data elements of the matrix.

* nrow is the number of rows to be created.

* ncol is the number of columns to be created.

* byrow is a logical clue. If TRUE then the input vector elements are arranged by row.

* dimname is the names assigned to the rows and columns.

#### Example
Create a matrix taking a vector of numbers as input.

In [4]:
# Elements are arranged sequentially by row.
M <- matrix(c(3:14), nrow = 4, byrow = TRUE)
print(M)

     [,1] [,2] [,3]
[1,]    3    4    5
[2,]    6    7    8
[3,]    9   10   11
[4,]   12   13   14


In [5]:
# Elements are arranged sequentially by column.
N <- matrix(c(3:14), nrow = 4, byrow = FALSE)
print(N)

     [,1] [,2] [,3]
[1,]    3    7   11
[2,]    4    8   12
[3,]    5    9   13
[4,]    6   10   14


In [6]:
N <- matrix(c(3:14),nrow=4,ncol=4, byrow=FALSE)
print(N)

     [,1] [,2] [,3] [,4]
[1,]    3    7   11    3
[2,]    4    8   12    4
[3,]    5    9   13    5
[4,]    6   10   14    6


In [7]:
rownames = c("row1","row2","row3","row4")
colnames = c("col1","col2","col3")

In [8]:
rownames

[1] "row1" "row2" "row3" "row4"

In [9]:
p <- matrix(c(3:14),nrow=4 , byrow=TRUE,dimnames = list(rownames,colnames))
print(p)

     col1 col2 col3
row1    3    4    5
row2    6    7    8
row3    9   10   11
row4   12   13   14


### Accessing Elements of a Matrix

Elements of a matrix can be accessed by using the column and row index of the element. We consider the matrix P above to find the specific elements below.

In [10]:
rownames = c("row1","row2","row3","row4")
colnames = c("col1","col2","col3")

p <- matrix(c(3:14),nrow=4,byrow=TRUE,dimnames=list(rownames,colnames))

In [11]:
print(p)

     col1 col2 col3
row1    3    4    5
row2    6    7    8
row3    9   10   11
row4   12   13   14


In [12]:
print(p[1,2])

[1] 4


In [13]:
print(p[3,1])

[1] 9


In [14]:
print(p[3,3])

[1] 11


#### Matrix Computations
Various mathematical operations are performed on the matrices using the R operators. The result of the operation is also a matrix.

The dimensions (number of rows and columns) should be same for the matrices involved in the operation.

In [15]:
matrix <-matrix(c(3,4,5,2,10,12),nrow=2)
print(matrix)

     [,1] [,2] [,3]
[1,]    3    5   10
[2,]    4    2   12


In [17]:
matrix1 <-matrix(c(1,2,3,4,5,6),nrow=2)

In [18]:
matrix1

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [19]:
matrix

[,1] [,2] [,3]
[1,] 3    5    10  
[2,] 4    2    12

In [20]:
result <- matrix + matrix1

In [21]:
print(resultlt)

     [,1] [,2] [,3]
[1,]    4    8   15
[2,]    6    6   18


In [22]:
result <- matrix - matrix1

In [23]:
result

[,1] [,2] [,3]
[1,] 2     2   5   
[2,] 2    -2   6

#### Matrix Multiplication & Division

In [24]:
matrix1 <- matrix(c(3, 9, -1, 4, 2, 6), nrow = 2)
print(matrix1)

     [,1] [,2] [,3]
[1,]    3   -1    2
[2,]    9    4    6


In [25]:
matrix2 <- matrix(c(5, 2, 0, 9, 3, 4), nrow = 2)
print(matrix2)

     [,1] [,2] [,3]
[1,]    5    0    3
[2,]    2    9    4


In [26]:
result <- matrix1 * matrix2
cat("Result of multiplication","\n")
print(result)

Result of multiplication 
     [,1] [,2] [,3]
[1,]   15    0    6
[2,]   18   36   24


In [27]:
# Divide the matrices
result <- matrix1 / matrix2
cat("Result of division","\n")
print(result)

Result of division 
     [,1]      [,2]      [,3]
[1,]  0.6      -Inf 0.6666667
[2,]  4.5 0.4444444 1.5000000
