# R - Arrays

Arrays are the R data objects which can store data in more than two dimensions. For example − If we create an array of dimension (2, 3, 4) then it creates 4 rectangular matrices each with 2 rows and 3 columns.

An array is created using the <b>array()</b> function. It takes vectors as input and uses the values in the dim parameter to create an array.

#### Example
The following example creates an array of two 3x3 matrices each with 3 rows and 3 columns.

In [5]:
vector1 <- c(5,9,3)
vector2 <- c(10,11,12,13,14,15)

# Take these vectors as input to the array.
result <- array(c(vector1,vector2),dim = c(3,3,3))
print(result)

, , 1

     [,1] [,2] [,3]
[1,]    5   10   13
[2,]    9   11   14
[3,]    3   12   15

, , 2

     [,1] [,2] [,3]
[1,]    5   10   13
[2,]    9   11   14
[3,]    3   12   15

, , 3

     [,1] [,2] [,3]
[1,]    5   10   13
[2,]    9   11   14
[3,]    3   12   15



### Naming Columns and Rows
We can give names to the rows, columns and matrices in the array by using the dimnames parameter.

In [6]:
vector1 <-c(5,9,2)
vector2 <-c(10,11,12,13,14,15)
col.names <- c('COL1','COL2','COL3')
row.names <- c('ROW1','ROW2','ROW3')
matrix.names <-c("MATRIX1","MATRIX2")

result <- array(c(vector1,vector2),dim=c(3,3,2),dimnames = list(row.names,col.names,matrix.names))

print(result)

, , MATRIX1

     COL1 COL2 COL3
ROW1    5   10   13
ROW2    9   11   14
ROW3    2   12   15

, , MATRIX2

     COL1 COL2 COL3
ROW1    5   10   13
ROW2    9   11   14
ROW3    2   12   15



### Accessing Array Elements

In [7]:
vector1 <-c(12,13,14,3)
vector2 <-c(10,20,30,40,50,60)
col.names <- c("COL1","COL2","COL3")
row.names <- c("ROW1","ROW2","ROW3")
matrix.names <- c('MATRIX1','MATRIX2')

result <- array(c(vector1,vector2),dim= c(3,3,2),dimnames = list(row.names,col.names,matrix.names))



In [9]:
# Print the third row of the second matrix of the array.
print(result[3,,2])

COL1 COL2 COL3 
  13   10   40 


In [10]:
# Print the element in the 1st row and 3rd column of the 1st matrix.
print(result[1,3,1])

[1] 30


In [11]:
# Print the 2nd Matrix.
print(result[,,2])

     COL1 COL2 COL3
ROW1   60   14   20
ROW2   12    3   30
ROW3   13   10   40


#### Manipulating Array Elements
As array is made up matrices in multiple dimensions, the operations on elements of array are carried out by accessing elements of the matrices.

In [18]:
vec1 <- c(4,9,12)
vec2 <- c(10,21,33,221,21,90)

In [19]:
array1 <- array(c(vec1,vec2),dim= c(3,3,2))

In [21]:
print(array1)

, , 1

     [,1] [,2] [,3]
[1,]    4   10  221
[2,]    9   21   21
[3,]   12   33   90

, , 2

     [,1] [,2] [,3]
[1,]    4   10  221
[2,]    9   21   21
[3,]   12   33   90



In [27]:
# Create two vectors of different lengths.
vector3 <- c(9,1,0)
vector4 <- c(6,0,11,3,14,1,2,6,9)
array2 <- array(c(vector3,vector4),dim = c(3,3,2))

In [28]:
print(array2)

, , 1

     [,1] [,2] [,3]
[1,]    9    6    3
[2,]    1    0   14
[3,]    0   11    1

, , 2

     [,1] [,2] [,3]
[1,]    2    9    6
[2,]    6    1    0
[3,]    9    0   11

